import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from '@/components/Footer'
import Navbar from '@/app/Navbar'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <title>Superheroes</title>
        <meta name="description" content="SPA Superheroes Marvel y DC" />
    </head>
    <body className={inter.className + ' bg-red flex h-screen flex-col justify-between'}>
        <Navbar />
        <Toaster position="top-center" reverseOrder={false} />
        <main className="mb-auto">{children}</main>
        <Footer />
    </body>
    </html>
  );
}
